### ISSUE TITLE
change from counting n to n_distinct(var_id)

### ISSUE THREAD

**Issue by nobert-mumo** [PeerChristensen/cohorts#2]
@PeerChristensen many thanks for this package. I used it for one of my analysis. One thing I found out in the source code is that the values being calculated seem to be a count of the rows (n) and not n_distinct(var_id). I believe to get the no of users we need to count the distinct user_ids ?

i.e. instead of 
` dplyr::summarise(users = dplyr::n()) %>%`

we have 

` dplyr::summarise(users = dplyr::n_distinct({{ id_var }})) %>%`

**Comment by PeerChristensen** [comment]
@nobert-mumo Thank you so much for pointing out this issue. I will make sure to include your suggested change in an upcoming release.
